"""Mapping FIXE colonne (lettre) -> role, genere depuis les en-tetes
reelles de 'Formation Geopunt 1.xlsx' (feuille 'Mesen', lignes 3=
categorie, 4=bracket) -- PAS un registre dynamique par icone comme
cote France (voir le plan : ce gabarit n'a aucune image ancree,
positions de colonnes stables par construction).

A VERIFIER contre le VRAI gabarit officiel si celui-ci differe de cet
exemple (colonnes ajoutees/deplacees) -- voir le plan, etape 5."""

from __future__ import annotations

from typing import Dict, Optional, TypedDict


class ColonneBE(TypedDict):
    role: str
    groupe: str
    categorie: str
    bracket: Optional[str]


COLONNES_BE: Dict[str, ColonneBE] = {
    'F': {'role': 'gewestplan__woongebieden', 'groupe': 'gewestplan', 'categorie': 'Woongebieden', 'bracket': None},
    'G': {'role': 'gewestplan__woonuitbreidingsgebieden', 'groupe': 'gewestplan', 'categorie': 'Woonuitbreidingsgebieden', 'bracket': None},
    'H': {'role': 'gewestplan__woonparken', 'groupe': 'gewestplan', 'categorie': 'Woonparken', 'bracket': None},
    'I': {'role': 'gewestplan__woongebieden_met_een_landelijk_karakter', 'groupe': 'gewestplan', 'categorie': 'Woongebieden met een landelijk karakter', 'bracket': None},
    'J': {'role': 'gewestplan__woongebieden_met_culturelke_historische_en_of_esthetisc', 'groupe': 'gewestplan', 'categorie': 'Woongebieden met culturelke, historische en/of esthetische waarde', 'bracket': None},
    'K': {'role': 'gewestplan__gebied_voor_kernontwikkeling', 'groupe': 'gewestplan', 'categorie': 'Gebied voor kernontwikkeling', 'bracket': None},
    'L': {'role': 'gewestplan__industriegebieden', 'groupe': 'gewestplan', 'categorie': 'Industriegebieden', 'bracket': None},
    'M': {'role': 'gewestplan__gebieden_voor_vervuilende_industrieen', 'groupe': 'gewestplan', 'categorie': 'Gebieden voor vervuilende industrieën', 'bracket': None},
    'N': {'role': 'gewestplan__gebieden_voor_milieubelastende_industrieen', 'groupe': 'gewestplan', 'categorie': 'Gebieden voor milieubelastende industrieën', 'bracket': None},
    'O': {'role': 'gewestplan__gebieden_voor_ambachtelijke_bedrijven_en_de_gebieden_vo', 'groupe': 'gewestplan', 'categorie': 'Gebieden voor ambachtelijke bedrijven en de gebieden voor kleine en middelgrote ondernemingen', 'bracket': None},
    'P': {'role': 'gewestplan__dienstverleningsgebieden_d', 'groupe': 'gewestplan', 'categorie': 'Dienstverleningsgebieden (D)', 'bracket': None},
    'Q': {'role': 'gewestplan__gebieden_hoofdzakelijk_besteld_voor_de_vestiging_van_gr', 'groupe': 'gewestplan', 'categorie': 'Gebieden hoofdzakelijk besteld voor de vestiging van grootwinkelbedrijven', 'bracket': None},
    'R': {'role': 'gewestplan__landelijke_gebieden', 'groupe': 'gewestplan', 'categorie': 'Landelijke gebieden', 'bracket': None},
    'S': {'role': 'gewestplan__agrarische_gebieden', 'groupe': 'gewestplan', 'categorie': 'Agrarische gebieden', 'bracket': None},
    'T': {'role': 'gewestplan__bosgebieden', 'groupe': 'gewestplan', 'categorie': 'Bosgebieden', 'bracket': None},
    'U': {'role': 'gewestplan__groengebieden', 'groupe': 'gewestplan', 'categorie': 'Groengebieden', 'bracket': None},
    'V': {'role': 'gewestplan__natuurgebieden_n', 'groupe': 'gewestplan', 'categorie': 'Natuurgebieden (N)', 'bracket': None},
    'W': {'role': 'gewestplan__natuurgebieden_met_wetenschappelijke_waarde_of_natuurre', 'groupe': 'gewestplan', 'categorie': 'Natuurgebieden met wetenschappelijke waarde of natuurreservaten ®', 'bracket': None},
    'X': {'role': 'gewestplan__parkgebieden_p', 'groupe': 'gewestplan', 'categorie': 'Parkgebieden (P)', 'bracket': None},
    'Y': {'role': 'gewestplan__buffe_rzones_t', 'groupe': 'gewestplan', 'categorie': 'Buffe"rzones (T)', 'bracket': None},
    'Z': {'role': 'gewestplan__landschappelijke_waarevolle_gebieden', 'groupe': 'gewestplan', 'categorie': 'Landschappelijke waarevolle gebieden', 'bracket': None},
    'AA': {'role': 'gewestplan__recreatiegebieden', 'groupe': 'gewestplan', 'categorie': 'Recreatiegebieden', 'bracket': None},
    'AB': {'role': 'gewestplan__landelijke_gebieen_met_toeristische_waarde', 'groupe': 'gewestplan', 'categorie': 'Landelijke gebieen met toeristische waarde', 'bracket': None},
    'AC': {'role': 'gewestplan__gebieden_voor_gemeenschapsvoorzieningen_en_openbare_nut', 'groupe': 'gewestplan', 'categorie': 'Gebieden voor gemeenschapsvoorzieningen en openbare nutsvoorzieningen', 'bracket': None},
    'AD': {'role': 'gewestplan__ontginningsgebieden', 'groupe': 'gewestplan', 'categorie': 'Ontginningsgebieden', 'bracket': None},
    'AE': {'role': 'gewestplan__gebieden_voor_dagrecreatie', 'groupe': 'gewestplan', 'categorie': 'Gebieden voor dagrecreatie', 'bracket': None},
    'AF': {'role': 'gewestplan__lokaal_bedrijventerrein_met_openbaar_karakter', 'groupe': 'gewestplan', 'categorie': 'lokaal bedrijventerrein met openbaar karakter', 'bracket': None},
    'AG': {'role': 'rup_region__lien_plan_d_execution_region', 'groupe': 'rup_region', 'categorie': "Lien plan d'execution REGION", 'bracket': None},
    'AH': {'role': 'rup_region__rup', 'groupe': 'rup_region', 'categorie': 'RUP', 'bracket': None},
    'AI': {'role': 'rup_region__wonen_zone_d_habitat', 'groupe': 'rup_region', 'categorie': "Wonen (zone d'habitat)", 'bracket': None},
    'AJ': {'role': 'rup_region__zone_voor_kleinschalig_wonen', 'groupe': 'rup_region', 'categorie': 'Zone voor kleinschalig wonen', 'bracket': None},
    'AK': {'role': 'rup_region__bedrijvigheid', 'groupe': 'rup_region', 'categorie': 'Bedrijvigheid', 'bracket': None},
    'AL': {'role': 'rup_region__bedrijvigheid_buffer', 'groupe': 'rup_region', 'categorie': 'Bedrijvigheid - Buffer', 'bracket': None},
    'AM': {'role': 'rup_region__recreatie', 'groupe': 'rup_region', 'categorie': 'Recreatie', 'bracket': None},
    'AN': {'role': 'rup_region__recreatie_natuurverwerving', 'groupe': 'rup_region', 'categorie': 'Recreatie (Natuurverwerving)', 'bracket': None},
    'AO': {'role': 'rup_region__landbouw_agrarisch_gebied', 'groupe': 'rup_region', 'categorie': 'Landbouw- agrarisch gebied', 'bracket': None},
    'AP': {'role': 'rup_region__landbouw_agrarische_bedrijvenzone', 'groupe': 'rup_region', 'categorie': 'Landbouw- agrarische bedrijvenzone', 'bracket': None},
    'AQ': {'role': 'rup_region__landbouw_bouwvrij_agrarisch_gebied', 'groupe': 'rup_region', 'categorie': 'Landbouw- bouwvrij agrarisch gebied', 'bracket': None},
    'AR': {'role': 'rup_region__landbouw_agrarisch_gebied_met_ecologisch_belang', 'groupe': 'rup_region', 'categorie': 'Landbouw- Agrarisch gebied met ecologisch belang', 'bracket': None},
    'AS': {'role': 'rup_region__bois_bos', 'groupe': 'rup_region', 'categorie': 'Bois (Bos)', 'bracket': None},
    'AT': {'role': 'rup_region__zone_verte_overig_groen_gemengd_openruimtegebied', 'groupe': 'rup_region', 'categorie': 'Zone verte (Overig groen - gemengd openruimtegebied)', 'bracket': None},
    'AU': {'role': 'rup_region__zone_verte_overig_groen_parkgebied', 'groupe': 'rup_region', 'categorie': 'Zone verte (Overig groen- parkgebied)', 'bracket': None},
    'AV': {'role': 'rup_region__zone_verte_overig_groen_gemengd_openruimtegebied_met_cu', 'groupe': 'rup_region', 'categorie': 'Zone verte - Overig groen-Gemengd openruimtegebied met cultuurhistorische waarde', 'bracket': None},
    'AW': {'role': 'rup_region__zone_verte_overig_groen_bestaande_vergunde_of_vergund_g', 'groupe': 'rup_region', 'categorie': 'Zone verte- Overig groen -bestaande, vergunde of vergund geachte weekendverblijven', 'bracket': None},
    'AX': {'role': 'rup_region__natuurgebied', 'groupe': 'rup_region', 'categorie': 'Natuurgebied', 'bracket': None},
    'AY': {'role': 'rup_region__natuurreservaat', 'groupe': 'rup_region', 'categorie': 'Natuurreservaat', 'bracket': None},
    'AZ': {'role': 'rup_region__gemeenschaps_en_nutsvoorzieningen', 'groupe': 'rup_region', 'categorie': 'Gemeenschaps- en nutsvoorzieningen', 'bracket': None},
    'BA': {'role': 'rup_region__gebied_voor_zuiveringsinfrastructuur_voor_afvalwater', 'groupe': 'rup_region', 'categorie': 'Gebied voor zuiveringsinfrastructuur voor afvalwater', 'bracket': None},
    'BB': {'role': 'rup_region__gebied_voor_infrastructuur_voor_duurzame_watervoorzieni', 'groupe': 'rup_region', 'categorie': 'gebied voor infrastructuur voor duurzame watervoorziening', 'bracket': None},
    'BC': {'role': 'rup_region__gebied_voor_de_winning_van_oppervlaktedelfstoffen', 'groupe': 'rup_region', 'categorie': 'gebied voor de winning van oppervlaktedelfstoffen', 'bracket': None},
    'BD': {'role': 'rup_region__gebied_voor_verwerking_van_oppervlaktedelfstoffen', 'groupe': 'rup_region', 'categorie': 'gebied voor verwerking van oppervlaktedelfstoffen', 'bracket': None},
    'BE': {'role': 'rup_region__gebied_voor_projectgrindwinning', 'groupe': 'rup_region', 'categorie': 'Gebied voor projectgrindwinning', 'bracket': None},
    'BF': {'role': 'rup_province__lien_plman_d_execution_province', 'groupe': 'rup_province', 'categorie': "Lien plman d'execution PROVINCE", 'bracket': None},
    'BG': {'role': 'rup_province__rup', 'groupe': 'rup_province', 'categorie': 'RUP', 'bracket': None},
    'BH': {'role': 'rup_province__wonen_zone_d_habitat', 'groupe': 'rup_province', 'categorie': "Wonen (zone d'habitat)", 'bracket': None},
    'BI': {'role': 'rup_province__zone_voor_kleinschalig_wonen', 'groupe': 'rup_province', 'categorie': 'Zone voor kleinschalig wonen', 'bracket': None},
    'BJ': {'role': 'rup_province__bedrijvigheid', 'groupe': 'rup_province', 'categorie': 'Bedrijvigheid', 'bracket': None},
    'BK': {'role': 'rup_province__bedrijvigheid_buffer', 'groupe': 'rup_province', 'categorie': 'Bedrijvigheid - Buffer', 'bracket': None},
    'BL': {'role': 'rup_province__recreatie', 'groupe': 'rup_province', 'categorie': 'Recreatie', 'bracket': None},
    'BM': {'role': 'rup_province__recreatie_natuurverwerving', 'groupe': 'rup_province', 'categorie': 'Recreatie (Natuurverwerving)', 'bracket': None},
    'BN': {'role': 'rup_province__landbouw_agrarisch_gebied', 'groupe': 'rup_province', 'categorie': 'Landbouw- agrarisch gebied', 'bracket': None},
    'BO': {'role': 'rup_province__landbouw_agrarische_bedrijvenzone', 'groupe': 'rup_province', 'categorie': 'Landbouw- agrarische bedrijvenzone', 'bracket': None},
    'BP': {'role': 'rup_province__landbouw_bouwvrij_agrarisch_gebied', 'groupe': 'rup_province', 'categorie': 'Landbouw- bouwvrij agrarisch gebied', 'bracket': None},
    'BQ': {'role': 'rup_province__landbouw_agrarisch_gebied_met_ecologisch_belang', 'groupe': 'rup_province', 'categorie': 'Landbouw- Agrarisch gebied met ecologisch belang', 'bracket': None},
    'BR': {'role': 'rup_province__bois_bos', 'groupe': 'rup_province', 'categorie': 'Bois (Bos)', 'bracket': None},
    'BS': {'role': 'rup_province__zone_verte_overig_groen_gemengd_openruimtegebied', 'groupe': 'rup_province', 'categorie': 'Zone verte (Overig groen - gemengd openruimtegebied)', 'bracket': None},
    'BT': {'role': 'rup_province__zone_verte_overig_groen_parkgebied', 'groupe': 'rup_province', 'categorie': 'Zone verte (Overig groen- parkgebied)', 'bracket': None},
    'BU': {'role': 'rup_province__zone_verte_overig_groen_gemengd_openruimtegebied_met_cu', 'groupe': 'rup_province', 'categorie': 'Zone verte - Overig groen-Gemengd openruimtegebied met cultuurhistorische waarde', 'bracket': None},
    'BV': {'role': 'rup_province__zone_verte_overig_groen_bestaande_vergunde_of_vergund_g', 'groupe': 'rup_province', 'categorie': 'Zone verte- Overig groen -bestaande, vergunde of vergund geachte weekendverblijven', 'bracket': None},
    'BW': {'role': 'rup_province__natuurgebied', 'groupe': 'rup_province', 'categorie': 'Natuurgebied', 'bracket': None},
    'BX': {'role': 'rup_province__natuurreservaat', 'groupe': 'rup_province', 'categorie': 'Natuurreservaat', 'bracket': None},
    'BY': {'role': 'rup_province__gemeenschaps_en_nutsvoorzieningen', 'groupe': 'rup_province', 'categorie': 'Gemeenschaps- en nutsvoorzieningen', 'bracket': None},
    'BZ': {'role': 'rup_province__gebied_voor_zuiveringsinfrastructuur_voor_afvalwater', 'groupe': 'rup_province', 'categorie': 'Gebied voor zuiveringsinfrastructuur voor afvalwater', 'bracket': None},
    'CA': {'role': 'rup_province__gebied_voor_infrastructuur_voor_duurzame_watervoorzieni', 'groupe': 'rup_province', 'categorie': 'gebied voor infrastructuur voor duurzame watervoorziening', 'bracket': None},
    'CB': {'role': 'rup_province__gebied_voor_de_winning_van_oppervlaktedelfstoffen', 'groupe': 'rup_province', 'categorie': 'gebied voor de winning van oppervlaktedelfstoffen', 'bracket': None},
    'CC': {'role': 'rup_province__gebied_voor_verwerking_van_oppervlaktedelfstoffen', 'groupe': 'rup_province', 'categorie': 'gebied voor verwerking van oppervlaktedelfstoffen', 'bracket': None},
    'CD': {'role': 'rup_province__gebied_voor_projectgrindwinning', 'groupe': 'rup_province', 'categorie': 'Gebied voor projectgrindwinning', 'bracket': None},
    'CE': {'role': 'rup_commune__lien_d_execution_commune', 'groupe': 'rup_commune', 'categorie': "Lien  d'execution commune", 'bracket': None},
    'CF': {'role': 'rup_commune__rup', 'groupe': 'rup_commune', 'categorie': 'RUP', 'bracket': None},
    'CG': {'role': 'rup_commune__wonen_zone_d_habitat', 'groupe': 'rup_commune', 'categorie': "Wonen (zone d'habitat)", 'bracket': None},
    'CH': {'role': 'rup_commune__zone_voor_kleinschalig_wonen', 'groupe': 'rup_commune', 'categorie': 'Zone voor kleinschalig wonen', 'bracket': None},
    'CI': {'role': 'rup_commune__bedrijvigheid', 'groupe': 'rup_commune', 'categorie': 'Bedrijvigheid', 'bracket': None},
    'CJ': {'role': 'rup_commune__bedrijvigheid_buffer', 'groupe': 'rup_commune', 'categorie': 'Bedrijvigheid - Buffer', 'bracket': None},
    'CK': {'role': 'rup_commune__recreatie', 'groupe': 'rup_commune', 'categorie': 'Recreatie', 'bracket': None},
    'CL': {'role': 'rup_commune__recreatie_natuurverwerving', 'groupe': 'rup_commune', 'categorie': 'Recreatie (Natuurverwerving)', 'bracket': None},
    'CM': {'role': 'rup_commune__landbouw_agrarisch_gebied', 'groupe': 'rup_commune', 'categorie': 'Landbouw- agrarisch gebied', 'bracket': None},
    'CN': {'role': 'rup_commune__landbouw_agrarische_bedrijvenzone', 'groupe': 'rup_commune', 'categorie': 'Landbouw- agrarische bedrijvenzone', 'bracket': None},
    'CO': {'role': 'rup_commune__landbouw_bouwvrij_agrarisch_gebied', 'groupe': 'rup_commune', 'categorie': 'Landbouw- bouwvrij agrarisch gebied', 'bracket': None},
    'CP': {'role': 'rup_commune__landbouw_agrarisch_gebied_met_ecologisch_belang', 'groupe': 'rup_commune', 'categorie': 'Landbouw- Agrarisch gebied met ecologisch belang', 'bracket': None},
    'CQ': {'role': 'rup_commune__bois_bos', 'groupe': 'rup_commune', 'categorie': 'Bois (Bos)', 'bracket': None},
    'CR': {'role': 'rup_commune__zone_verte_overig_groen_gemengd_openruimtegebied', 'groupe': 'rup_commune', 'categorie': 'Zone verte (Overig groen - gemengd openruimtegebied)', 'bracket': None},
    'CS': {'role': 'rup_commune__zone_verte_overig_groen_parkgebied', 'groupe': 'rup_commune', 'categorie': 'Zone verte (Overig groen- parkgebied)', 'bracket': None},
    'CT': {'role': 'rup_commune__zone_verte_overig_groen_gemengd_openruimtegebied_met_cu', 'groupe': 'rup_commune', 'categorie': 'Zone verte - Overig groen-Gemengd openruimtegebied met cultuurhistorische waarde', 'bracket': None},
    'CU': {'role': 'rup_commune__zone_verte_overig_groen_bestaande_vergunde_of_vergund_g', 'groupe': 'rup_commune', 'categorie': 'Zone verte- Overig groen -bestaande, vergunde of vergund geachte weekendverblijven', 'bracket': None},
    'CV': {'role': 'rup_commune__natuurgebied', 'groupe': 'rup_commune', 'categorie': 'Natuurgebied', 'bracket': None},
    'CW': {'role': 'rup_commune__natuurreservaat', 'groupe': 'rup_commune', 'categorie': 'Natuurreservaat', 'bracket': None},
    'CX': {'role': 'rup_commune__gemeenschaps_en_nutsvoorzieningen', 'groupe': 'rup_commune', 'categorie': 'Gemeenschaps- en nutsvoorzieningen', 'bracket': None},
    'CY': {'role': 'rup_commune__gebied_voor_zuiveringsinfrastructuur_voor_afvalwater', 'groupe': 'rup_commune', 'categorie': 'Gebied voor zuiveringsinfrastructuur voor afvalwater', 'bracket': None},
    'CZ': {'role': 'rup_commune__gebied_voor_infrastructuur_voor_duurzame_watervoorzieni', 'groupe': 'rup_commune', 'categorie': 'gebied voor infrastructuur voor duurzame watervoorziening', 'bracket': None},
    'DA': {'role': 'rup_commune__gebied_voor_de_winning_van_oppervlaktedelfstoffen', 'groupe': 'rup_commune', 'categorie': 'gebied voor de winning van oppervlaktedelfstoffen', 'bracket': None},
    'DB': {'role': 'rup_commune__gebied_voor_verwerking_van_oppervlaktedelfstoffen', 'groupe': 'rup_commune', 'categorie': 'gebied voor verwerking van oppervlaktedelfstoffen', 'bracket': None},
    'DC': {'role': 'rup_commune__gebied_voor_projectgrindwinning', 'groupe': 'rup_commune', 'categorie': 'Gebied voor projectgrindwinning', 'bracket': None},
    'DD': {'role': 'watertoets_simple__mogelijk_overstromingsgevoelig', 'groupe': 'watertoets_simple', 'categorie': 'Mogelijk overstromingsgevoelig', 'bracket': None},
    'DE': {'role': 'watertoets_simple__effectief_overstromingsgevoelig', 'groupe': 'watertoets_simple', 'categorie': 'Effectief overstromingsgevoelig', 'bracket': None},
    'DF': {'role': 'eaux_beheergebieden__beheergebieden_beheerovereenkomst_waterwaliteit', 'groupe': 'eaux_beheergebieden', 'categorie': 'Beheergebieden beheerovereenkomst waterwaliteit', 'bracket': None},
    'DG': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_pluvial__geen_overstroming_gemodelleerd', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden  Pluvial', 'bracket': 'Geen overstroming gemodelleerd'},
    'DH': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_pluvial__kleine_kans_op_overstromingen_onder_klimaatverandering', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden  Pluvial', 'bracket': 'Kleine kans op overstromingen onder klimaatverandering'},
    'DI': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_pluvial__kleine_kans_op_overstromingen', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden  Pluvial', 'bracket': 'Kleine kans op overstromingen'},
    'DJ': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_pluvial__middelgrote_kans_op_overstromingen', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden  Pluvial', 'bracket': 'Middelgrote kans op overstromingen'},
    'DK': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_fluvial__geen_overstroming_gemodelleerd', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden Fluvial', 'bracket': 'Geen overstroming gemodelleerd'},
    'DL': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_fluvial__kleine_kans_op_overstromingen_onder_klimaatverandering', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden Fluvial', 'bracket': 'Kleine kans op overstromingen onder klimaatverandering'},
    'DM': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_fluvial__kleine_kans_op_overstromingen', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden Fluvial', 'bracket': 'Kleine kans op overstromingen'},
    'DN': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_fluvial__middelgrote_kans_op_overstromingen', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden Fluvial', 'bracket': 'Middelgrote kans op overstromingen'},
    'DO': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_vanuit_zee__geen_overstroming_gemodelleerd', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden vanuit zee', 'bracket': 'Geen overstroming gemodelleerd'},
    'DP': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_vanuit_zee__kleine_kans_op_overstromingen_onder_klimaatverandering', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden vanuit zee', 'bracket': 'Kleine kans op overstromingen onder klimaatverandering'},
    'DQ': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_vanuit_zee__kleine_kans_op_overstromingen', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden vanuit zee', 'bracket': 'Kleine kans op overstromingen'},
    'DR': {'role': 'watertoets_detail__overstromingsgevoelige_gebieden_vanuit_zee__middelgrote_kans_op_overstromingen', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgevoelige gebieden vanuit zee', 'bracket': 'Middelgrote kans op overstromingen'},
    'DS': {'role': 'watertoets_detail__afgebakende_overstromingsgebieden_en_oeverzones__iwb_oeverzonei', 'groupe': 'watertoets_detail', 'categorie': 'Afgebakende overstromingsgebieden en oeverzones', 'bracket': 'IWB OeverzoneI'},
    'DT': {'role': 'watertoets_detail__afgebakende_overstromingsgebieden_en_oeverzones__wb_overstromingsgebied', 'groupe': 'watertoets_detail', 'categorie': 'Afgebakende overstromingsgebieden en oeverzones', 'bracket': 'WB Overstromingsgebied'},
    'DU': {'role': 'watertoets_detail__signaalgebieden__bouwvrije_opgave', 'groupe': 'watertoets_detail', 'categorie': 'Signaalgebieden', 'bracket': 'Bouwvrije opgave'},
    'DV': {'role': 'watertoets_detail__signaalgebieden__verscherpte_watertoets', 'groupe': 'watertoets_detail', 'categorie': 'Signaalgebieden', 'bracket': 'Verscherpte watertoets'},
    'DW': {'role': 'watertoets_detail__grond_waterstromingsgevoelige_gebieden', 'groupe': 'watertoets_detail', 'categorie': 'Grond waterstromingsgevoelige gebieden', 'bracket': None},
    'DX': {'role': 'watertoets_detail__van_natuur_overstroombare_gebieden', 'groupe': 'watertoets_detail', 'categorie': 'Van Natuur overstroombare gebieden', 'bracket': None},
    'DY': {'role': 'watertoets_detail__risicozones_voor_overstromingen_nieuwe_en_bevestigde_ri', 'groupe': 'watertoets_detail', 'categorie': 'Risicozones voor overstromingen: nieuwe en bevestigde risocozones', 'bracket': None},
    'DZ': {'role': 'watertoets_detail__recent_overstromde_gebieden', 'groupe': 'watertoets_detail', 'categorie': 'Recent overstromde gebieden', 'bracket': None},
    'EA': {'role': 'watertoets_detail__overstromingsgebieden_en_oeverzones_integraal_waterbele', 'groupe': 'watertoets_detail', 'categorie': 'Overstromingsgebieden en oeverzones - integraal waterbeleid', 'bracket': None},
    'EB': {'role': 'watertoets_detail__grondwaterwingebieden_en_beschermingszones', 'groupe': 'watertoets_detail', 'categorie': 'Grondwaterwingebieden en beschermingszones', 'bracket': None},
    'EC': {'role': 'watertoets_detail__infiltratiegevoelige_bodems', 'groupe': 'watertoets_detail', 'categorie': 'Infiltratiegevoelige bodems', 'bracket': None},
    'ED': {'role': 'erosion_afstroming__afstromingskaart_enkelvoudige_stroomlijnen__0_5_5_ha', 'groupe': 'erosion_afstroming', 'categorie': 'Afstromingskaart (enkelvoudige stroomlijnen)', 'bracket': '0,5-5 ha'},
    'EE': {'role': 'erosion_afstroming__afstromingskaart_enkelvoudige_stroomlijnen__5_10_ha', 'groupe': 'erosion_afstroming', 'categorie': 'Afstromingskaart (enkelvoudige stroomlijnen)', 'bracket': '5-10 ha'},
    'EF': {'role': 'erosion_afstroming__afstromingskaart_enkelvoudige_stroomlijnen__10_20ha', 'groupe': 'erosion_afstroming', 'categorie': 'Afstromingskaart (enkelvoudige stroomlijnen)', 'bracket': '10-20ha'},
    'EG': {'role': 'erosion_afstroming__afstromingskaart_enkelvoudige_stroomlijnen__20_50_ha', 'groupe': 'erosion_afstroming', 'categorie': 'Afstromingskaart (enkelvoudige stroomlijnen)', 'bracket': '20-50 ha'},
    'EH': {'role': 'erosion_afstroming__afstromingskaart_enkelvoudige_stroomlijnen__50_100_ha', 'groupe': 'erosion_afstroming', 'categorie': 'Afstromingskaart (enkelvoudige stroomlijnen)', 'bracket': '50-100 ha'},
    'EI': {'role': 'erosion_afstroming__afstromingskaart_enkelvoudige_stroomlijnen__100_ha', 'groupe': 'erosion_afstroming', 'categorie': 'Afstromingskaart (enkelvoudige stroomlijnen)', 'bracket': '>100 ha'},
    'EJ': {'role': 'bodem__andere_erosiegerelateerde_gronden', 'groupe': 'bodem', 'categorie': 'Andere erosiegerelateerde gronden', 'bracket': None},
    'EK': {'role': 'bodem__gekarteerde_grondverschuivingen', 'groupe': 'bodem', 'categorie': 'Gekarteerde grondverschuivingen', 'bracket': None},
    'EL': {'role': 'bodem__gevoeligheid_voor_grondverschuivingen', 'groupe': 'bodem', 'categorie': 'Gevoeligheid voor grondverschuivingen', 'bracket': None},
    'EM': {'role': 'bodem__potentiele_bodemerosiekaart_per_perceel_2021', 'groupe': 'bodem', 'categorie': 'Potentiële bodemerosiekaart per perceel 2021', 'bracket': None},
    'EN': {'role': 'bodem__watertoets', 'groupe': 'bodem', 'categorie': 'Watertoets', 'bracket': None},
    'EO': {'role': 'economie_bedrijven__aangeboden_bedrijventerreinperceel', 'groupe': 'economie_bedrijven', 'categorie': 'Aangeboden bedrijventerreinperceel', 'bracket': None},
    'EP': {'role': 'economie_bedrijven__bedrijventerrein', 'groupe': 'economie_bedrijven', 'categorie': 'Bedrijventerrein', 'bracket': None},
    'EQ': {'role': 'economie_bedrijven__beheerde_bedrijvenzone', 'groupe': 'economie_bedrijven', 'categorie': 'Beheerde bedrijvenzone', 'bracket': None},
    'ER': {'role': 'economie_bedrijven__ontwikkelbare_bedrijvenzone', 'groupe': 'economie_bedrijven', 'categorie': 'Ontwikkelbare bedrijvenzone', 'bracket': None},
    'ES': {'role': 'economie_bedrijven__planningszone_met_economische_bestemming', 'groupe': 'economie_bedrijven', 'categorie': 'Planningszone met economische bestemming', 'bracket': None},
    'ET': {'role': 'economie_bedrijven__brownfieldconvenanten', 'groupe': 'economie_bedrijven', 'categorie': 'Brownfieldconvenanten', 'bracket': None},
    'EU': {'role': 'economie_bedrijven__steunzone', 'groupe': 'economie_bedrijven', 'categorie': 'Steunzone', 'bracket': None},
    'EV': {'role': 'economie_bedrijven__seveso_inrichingen', 'groupe': 'economie_bedrijven', 'categorie': 'Seveso inrichingen', 'bracket': None},
    'EW': {'role': 'economie_bedrijven__consultatie_zone_van_seveso_inrichtingen', 'groupe': 'economie_bedrijven', 'categorie': 'Consultatie zone van Seveso-inrichtingen', 'bracket': None},
    'EX': {'role': 'landinrichting__landinrichting_in_onderzoek', 'groupe': 'landinrichting', 'categorie': 'Landinrichting in onderzoek', 'bracket': None},
    'EY': {'role': 'landinrichting__vastgesteld_landinrichtingsproject', 'groupe': 'landinrichting', 'categorie': 'Vastgesteld landinrichtingsproject', 'bracket': None},
    'EZ': {'role': 'landinrichting__landinrichtingsplan', 'groupe': 'landinrichting', 'categorie': 'Landinrichtingsplan', 'bracket': None},
    'FA': {'role': 'landinrichting__natuurinrichting', 'groupe': 'landinrichting', 'categorie': 'Natuurinrichting', 'bracket': None},
    'FB': {'role': 'landinrichting__ruilverkaveling_ruilverkaveling_van_landeigendommen_uit', 'groupe': 'landinrichting', 'categorie': 'Ruilverkaveling\n(Ruilverkaveling van landeigendommen uit kracht van wet)', 'bracket': None},
    'FC': {'role': 'landschap__fysische_systeemeenheden', 'groupe': 'landschap', 'categorie': 'Fysische systeemeenheden', 'bracket': None},
    'FD': {'role': 'landschap__traditionele_landschappen', 'groupe': 'landschap', 'categorie': 'Traditionele landschappen', 'bracket': None},
    'FE': {'role': 'natuur_milieu__beheergebieden_natura_2000_soorten', 'groupe': 'natuur_milieu', 'categorie': 'Beheergebieden Natura 2000-soorten', 'bracket': None},
    'FF': {'role': 'natuur_milieu__bosreservaten', 'groupe': 'natuur_milieu', 'categorie': 'Bosreservaten', 'bracket': None},
    'FG': {'role': 'natuur_milieu__erkende_natuurreservaten', 'groupe': 'natuur_milieu', 'categorie': 'Erkende Natuurreservaten', 'bracket': None},
    'FH': {'role': 'natuur_milieu__gebieden_duinendecreet', 'groupe': 'natuur_milieu', 'categorie': 'Gebieden duinendecreet', 'bracket': None},
    'FI': {'role': 'natuur_milieu__gebieden_van_het_ven_en_het_ivon_ven_en_het_ivon', 'groupe': 'natuur_milieu', 'categorie': 'Gebieden van het VEN en het IVON\n(VEN en het IVON)', 'bracket': None},
    'FJ': {'role': 'natuur_milieu__habitatrichtlijngebieden', 'groupe': 'natuur_milieu', 'categorie': 'Habitatrichtlijngebieden', 'bracket': None},
    'FK': {'role': 'natuur_milieu__vogelrichtlijngebieden', 'groupe': 'natuur_milieu', 'categorie': 'Vogelrichtlijngebieden', 'bracket': None},
    'FL': {'role': 'geluid_wegen__geluidsbelasting_belangrijke_wegen_lnight_2021_expositi__50_55_db_decibel', 'groupe': 'geluid_wegen', 'categorie': 'Geluidsbelasting belangrijke wegen Lnight 2021\n  (Exposition au bruit- routes)', 'bracket': '50-55 dB (décibel)'},
    'FM': {'role': 'geluid_wegen__geluidsbelasting_belangrijke_wegen_lnight_2021_expositi__55_60_db', 'groupe': 'geluid_wegen', 'categorie': 'Geluidsbelasting belangrijke wegen Lnight 2021\n  (Exposition au bruit- routes)', 'bracket': '55-60 dB'},
    'FN': {'role': 'geluid_wegen__geluidsbelasting_belangrijke_wegen_lnight_2021_expositi__60_65_db', 'groupe': 'geluid_wegen', 'categorie': 'Geluidsbelasting belangrijke wegen Lnight 2021\n  (Exposition au bruit- routes)', 'bracket': '60-65 dB'},
    'FO': {'role': 'geluid_wegen__geluidsbelasting_belangrijke_wegen_lnight_2021_expositi__65_70_db', 'groupe': 'geluid_wegen', 'categorie': 'Geluidsbelasting belangrijke wegen Lnight 2021\n  (Exposition au bruit- routes)', 'bracket': '65-70 dB'},
    'FP': {'role': 'geluid_wegen__geluidsbelasting_belangrijke_wegen_lnight_2021_expositi__70_db', 'groupe': 'geluid_wegen', 'categorie': 'Geluidsbelasting belangrijke wegen Lnight 2021\n  (Exposition au bruit- routes)', 'bracket': '> 70 dB'},
    'FQ': {'role': 'geluid_luchthaven__geluidsbelasting_belangrijke_luchthaven_s_lnight_2021_e__50_55_db_decibel', 'groupe': 'geluid_luchthaven', 'categorie': 'Geluidsbelasting belangrijke luchthaven(s) Lnight 2021(Exposition au bruit- voies ferrées)', 'bracket': '50-55 dB (décibel)'},
    'FR': {'role': 'geluid_luchthaven__geluidsbelasting_belangrijke_luchthaven_s_lnight_2021_e__55_60_db', 'groupe': 'geluid_luchthaven', 'categorie': 'Geluidsbelasting belangrijke luchthaven(s) Lnight 2021(Exposition au bruit- voies ferrées)', 'bracket': '55-60 dB'},
    'FS': {'role': 'geluid_luchthaven__geluidsbelasting_belangrijke_luchthaven_s_lnight_2021_e__60_65_db', 'groupe': 'geluid_luchthaven', 'categorie': 'Geluidsbelasting belangrijke luchthaven(s) Lnight 2021(Exposition au bruit- voies ferrées)', 'bracket': '60-65 dB'},
    'FT': {'role': 'geluid_luchthaven__geluidsbelasting_belangrijke_luchthaven_s_lnight_2021_e__65_70_db', 'groupe': 'geluid_luchthaven', 'categorie': 'Geluidsbelasting belangrijke luchthaven(s) Lnight 2021(Exposition au bruit- voies ferrées)', 'bracket': '65-70 dB'},
    'FU': {'role': 'geluid_luchthaven__geluidsbelasting_belangrijke_luchthaven_s_lnight_2021_e__70_db', 'groupe': 'geluid_luchthaven', 'categorie': 'Geluidsbelasting belangrijke luchthaven(s) Lnight 2021(Exposition au bruit- voies ferrées)', 'bracket': '> 70 dB'},
    'FV': {'role': 'geluid_spoorwegen__geluidsbelasting_geluidsbelasting_belangrijke_spoorwege__50_55_db_decibel', 'groupe': 'geluid_spoorwegen', 'categorie': 'Geluidsbelasting Geluidsbelasting belangrijke spoorwegen Lden 2021 (Exposition au bruit- aéroport)', 'bracket': '50-55 dB (décibel)'},
    'FW': {'role': 'geluid_spoorwegen__geluidsbelasting_geluidsbelasting_belangrijke_spoorwege__55_60_db', 'groupe': 'geluid_spoorwegen', 'categorie': 'Geluidsbelasting Geluidsbelasting belangrijke spoorwegen Lden 2021 (Exposition au bruit- aéroport)', 'bracket': '55-60 dB'},
    'FX': {'role': 'geluid_spoorwegen__geluidsbelasting_geluidsbelasting_belangrijke_spoorwege__60_65_db', 'groupe': 'geluid_spoorwegen', 'categorie': 'Geluidsbelasting Geluidsbelasting belangrijke spoorwegen Lden 2021 (Exposition au bruit- aéroport)', 'bracket': '60-65 dB'},
    'FY': {'role': 'geluid_spoorwegen__geluidsbelasting_geluidsbelasting_belangrijke_spoorwege__65_70_db', 'groupe': 'geluid_spoorwegen', 'categorie': 'Geluidsbelasting Geluidsbelasting belangrijke spoorwegen Lden 2021 (Exposition au bruit- aéroport)', 'bracket': '65-70 dB'},
    'FZ': {'role': 'geluid_spoorwegen__geluidsbelasting_geluidsbelasting_belangrijke_spoorwege__70_db', 'groupe': 'geluid_spoorwegen', 'categorie': 'Geluidsbelasting Geluidsbelasting belangrijke spoorwegen Lden 2021 (Exposition au bruit- aéroport)', 'bracket': '> 70 dB'},
    'GA': {'role': 'bodem_verontreiniging__bodem_is_licht_verontreinigd', 'groupe': 'bodem_verontreiniging', 'categorie': 'Bodem is licht verontreinigd', 'bracket': None},
    'GB': {'role': 'bodem_verontreiniging__bodem_is_proper', 'groupe': 'bodem_verontreiniging', 'categorie': 'Bodem is proper', 'bracket': None},
    'GC': {'role': 'bodem_verontreiniging__bodem_is_verontreinigd', 'groupe': 'bodem_verontreiniging', 'categorie': 'Bodem is verontreinigd', 'bracket': None},
    'GD': {'role': 'bodem_verontreiniging__bodeminfo_wordt_gecheckt', 'groupe': 'bodem_verontreiniging', 'categorie': 'Bodeminfo wordt gecheckt', 'bracket': None},
    'GE': {'role': 'bodem_verontreiniging__mogelijke_risicogrond', 'groupe': 'bodem_verontreiniging', 'categorie': 'Mogelijke risicogrond', 'bracket': None},
    'GF': {'role': 'bodem_verontreiniging__geen_bodeminfo', 'groupe': 'bodem_verontreiniging', 'categorie': 'Geen bodeminfo', 'bracket': None},
    'GG': {'role': 'logement__woningbouwgebieden', 'groupe': 'logement', 'categorie': 'Woningbouwgebieden', 'bracket': None},
    'GH': {'role': 'logement__woonvernieuwingsgebieden', 'groupe': 'logement', 'categorie': 'Woonvernieuwingsgebieden', 'bracket': None},
}

# Total colonnes dynamiques (F -> GH) : 185
